version: "3"

services:
  database:
    image: mysql
    restart: always
    environment: # 해당 이미지가 사용할 환경 변수 설정
      MYSQL_DATABASE: commercedb
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  redis:
    image: redis
    restart: always
    ports:
      - "6379"
    networks:
      - test_network

  application:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/commercedb?createDatabaseIfNotExist=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis
    networks:
      - test_network

# 컨테이너 간 통신을 컨테이너의 이름으로 하기 위해서는 커스텀 네트워크를 생성하고
# 해당 네트워크에 컨테이너를 생성해야 함
networks:
  test_network:

volumes:
  mysql-data:
