spring:
  profiles:
    active: local
    group:
      local: "local-config, common"
      test: "test-config, common"
---
spring:
  config:
    activate:
      on-profile: local-config
  redis:
    host: 127.0.0.1
    port: 6379

---
spring:
  config:
    activate:
      on-profile: test-config
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:///commercedb
  redis:
    host: 127.0.0.1
    port: 6379
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
  main:
    allow-bean-definition-overriding: true
  batch:
    jdbc: # 임베디드 데이터 소스를 사용하지 않을 때도 활성화 가능
      initialize-schema: always
    job:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8080
jwt:
  secret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345

