spring:
  profiles:
    group:
      "local": "local-config, common"
      "test": "test-config, common"
---
spring:
  config:
    active:
      on-profile: "local-config"
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
---
spring:
  config:
    active:
      on-profile: "test-config"
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:///commercedb
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: false
---
spring:
  config:
    active:
      on-profile: "common"
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true

server:
  port: 8080
jwt:
  secret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345

#spring.datasource.url=jdbc:mysql://localhost:3307/commercedb?createDatabaseIfNotExist=true&autoReconnect=true
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver